### ISSUE TITLE
Is this working with .authinfo?

### ISSUE THREAD

**Issue by amno1** [KarimAziev/igist#8]
Have you been using this lately?

I have a GH token and have setup .authinfo according the instructions in the readme: amno1^igist and a GH token with the gist priviledge, however when I run any of listing functions, which all are routing through igist-list-request, I get a json filled with data from a bunch bot accounts?

```
[{"url":"https://api.github.com/gists/20fb17a13c2e219a0f4d2990d6fd106d","forks_url":"https://api.github.com/gists/20fb17a13c2e219a0f4d2990d6fd106d/forks","commits_url":"https://api.github.com/gists/20fb17a13c2e219a0f4d2990d6fd106d/commits","id":"20fb17a13c2e219a0f4d2990d6fd106d","node_id":"G_kwDOCQw3VdoAIDIwZmIxN2ExM2MyZTIxOWEwZjRkMjk5MGQ2ZmQxMDZk","git_pull_url":"https://gist.github.com/20fb17a13c2e219a0f4d2990d6fd106d.git","git_push_url":"https://gist.github.com/20fb17a13c2e219a0f4d2990d6fd106d.git","html_url":"https://gist.github.com/MixDark/20fb17a13c2e219a0f4d2990d6fd106d","files":{"flor_espiral.py":{"filename":"flor_espiral.py","type":"application/x-python","language":"Python","raw_url":"https://gist.githubusercontent.com/MixDark/20fb17a13c2e219a0f4d2990d6fd106d/raw/b284dfe1b2ab8909282e9cba673e071fd9739885/flor_espiral.py","size":347}},"public":true,"created_at":"2024-06-22T14:07:59Z","updated_at":"2024-06-22T14:07:59Z","description":"Flor espiral","comments":0,"user":null,"comments_url":"https://api.github.com/gists/20fb17a13c2e219a0f4d2990d6fd106d/comments","owner":{"login":"MixDark","id":151795541,"node_id":"U_kgDOCQw3VQ","avatar_url":"https://avatars.githubusercontent.com/u/151795541?v=4","gravatar_id":"","url":"https://api.github.com/users/MixDark","html_url":"https://github.com/MixDark","followers_url":"https://api.github.com/users/MixDark/followers","following_url":"https://api.github.com/users/MixDark/following{/other_user}","gists_url":"https://api.github.com/users/MixDark/gists{/gist_id}","starred_url":"https://api.github.com/users/MixDark/starred{/owner}{/repo}",
```

The above is just few first lines. Any idea, why is that?

**Comment by KarimAziev** [comment]
From your description, it seems like you might be seeing gists from other users instead of your own. This could happen if the command you executed lists public gists or gists from other users.

If you executed `M-x igist-explore-public-gists` or `M-x igist-list-other-user-gists`, these commands are designed to list gists from other users or public gists, respectively. To list your own gists, you should use `M-x igist-list-gists`. This command will display gists of the user specified in `igist-current-user-name`.

You can also check the buffer name where gists of other users are listed:
- The buffer for public gists is named `*igist-explore*`.
- The buffer for a specific user's gists is named `*igist-USERNAME*`.

If the problem persists, here are a few points to clarify and check:

**Check `igist-current-user-name`**: Ensure that the value of `igist-current-user-name` is set to your correct GitHub username, e.g., `amno1`. When you invoke `M-x igist-dispatch`, ensure that the login name displayed is correct.

**Temporary Token Setting**: Temporarily try to set `igist-auth-marker` to your GitHub OAuth token as a string directly in your Emacs configuration to rule out any issues with `.authinfo`:
   ```elisp
   (setq igist-current-user-name "your-github-username")
   (setq igist-auth-marker "your-github-oauth-token")
   ```

**Verify `.authinfo` Configuration**: Ensure your `.authinfo` file is correctly configured. It should have an entry like:
   ```
   machine api.github.com login YOUR-GITHUB-USERNAME^igist password YOUR-GITHUB-TOKEN
   ```

Try running `M-x igist-list-gists` and see if it lists your gists correctly. If the issue persists, please provide more details about the exact commands you executed and any relevant configuration settings.

**Comment by amno1** [comment]
Thanks for very fast response, and the work too.

No I haven't try to explore other users. I just tried to see my gists with M-x igist-list-gists.

I did all you say even before I even posted. The user name is correctly displaying my nick "amno1". The first time I run it, igist asked me for the user name and correctly suggested my amno1^igist. .authinfo is correctly setup, I have other stuff in there which Gnus also uses for smtp/imap and it works correctly.

I also edebugged your igist-list-request which seems to be the workhorse that calls igist--request, and I can see that all data is correctly setup with my nick, and so on. However the rendered list is empty. Even if I would be downloading other user's gists, it should render those gists? However, it ends in the error part of the callback always (condition-case nil ....).

When it comes to buffers there is only *igist-amno1*. 

[Here is a screenshot from edebug](https://imgur.com/pm3uKYK), so you can see arguments passed to igist--request. I can send you copy-paste from the message buffer if you want, but you see in the screenshot.

I don't have so much more time today, tried to find quickly what was wrong, but I am not really sure.

Thanks for the work, and for the help. Would be nice if the package works, I would to use it for fast copy-pasting to gh gists as a sort of scratch pad of snippets (or something in that style).

Forgott to say: even nick and token pasted into the vars, it didn't work, the list is always empty. Haven't checked what json it gets.

**Comment by KarimAziev** [comment]
Thanks for your detailed description!

If your Emacs doesn't have native JSON support, please pull the latest version of `igist`. I believe I have fixed the issue.

You can check for native JSON support with the following code:

```elisp
(and (fboundp 'json-parse-string)
     (fboundp 'json-available-p)
     (json-available-p))
```

If the problem still persists, we will find a solution. Please enable the debug mode by setting `(setq igist-debug t)` and then share the contents of the `*IGIST-DEBUG*` buffer. Additionally, it would be helpful to know the version of Emacs you are using, as well as the version of `ghub.el`.

**Comment by amno1** [comment]
Yes, that seem to be a problem. I tested today from my Linux build, which I compile with json support, and it seem to work. 

Sorry, I was totally forgetting that json parsing could be a problem. Thank you for the fast and response, and an interesting package.
